<?php if(\Code\Session\Flash::has('success')): ?>
<div class="alert alert-success">
    <?=\Code\Session\Flash::get('success');?>
</div>
<?php endif;?>

<?php if(\Code\Session\Flash::has('warning')): ?>
<div class="alert alert-warning">
    <?=\Code\Session\Flash::get('warning');?>
</div>
<?php endif;?>


<?php if(\Code\Session\Flash::has('error')): ?>
<div class="alert alert-error">
    <?=\Code\Session\Flash::get('error');?>
</div>
<?php endif;?>