<?php require TEMPLATES . 'includes/header.phtml';?>

<div class="row front">
    <?php foreach($products as $key => $product):?>
        
        <div class="col-4">
        
            <div class="card">
            
                <img src="https://via.placeholder.com/650x300.png?text=<?=$product->name;?>" alt="<?=$product->name;?>" class="img-fluid">
            
                <div class="card-body">
                    <h2><?=$product->name;?></h2>

                    <p><?=$product->description;?></p>

                    <h3>R$ <?=$product->price;?></h3>

                    <a href="<?=HOME;?>product/show/<?=$product->slug;?>" class="btn btn-success btn-sm">Ver Produto</a>
                </div>
            
            </div>

        </div>
        <?php if(($key + 1) % 3 == 0):?> </div> <div class="row front"> <?php endif;?>
    <?php endforeach;?>
</div>

<?php require TEMPLATES . 'includes/footer.phtml';?>