<?php require TEMPLATES . 'includes/header.phtml';?>

<div class="row">
    <?php foreach($products as $key => $product):?>
        
        <div class="col-4">
            <img src="https://via.placeholder.com/650x300.png?text=<?=$product->name;?>" alt="<?=$product->name;?>" class="img-fluid">
            
            <h2><?=$product->name;?></h2>

            <p><?=$product->description;?></p>

            <h3>R$ <?=$product->price;?></h3>

        </div>
        <?php if(($key + 1) % 3 == 0):?> </div> <div class="row"> <?php endif;?>
    <?php endforeach;?>
</div>

<?php require TEMPLATES . 'includes/footer.phtml';?>